// Generated by tools/aerials/build.mjs. Do not edit by hand.
// Imagery: USDA NAIP via USGS (public domain). Outlines: Sonoma County CDR_Parcels, projected
// into image pixels (Web Mercator, y down). Planning purposes only, not parcel-specific decisions.

export const AERIAL_CREDIT = "Aerial: USDA NAIP via USGS (public domain)" as const;

export interface LotAerial {
  readonly propertyId: string;
  /** Null when the parcel is unresolved: no photo is shown. */
  readonly src: string | null;
  readonly width: number;
  readonly height: number;
  /** Parcel outline in image pixels [x, y], y down. Null when the parcel is unresolved. */
  readonly outline: readonly (readonly [number, number])[] | null;
  readonly credit: typeof AERIAL_CREDIT;
}

export interface HeroAerial {
  readonly src: string;
  readonly width: number;
  readonly height: number;
  readonly credit: typeof AERIAL_CREDIT;
}

export const LOT_AERIALS: readonly LotAerial[] = [
  {
    "propertyId": "cb24261a-6334-4000-81ee-f99fb9df163c",
    "src": "/aerials/cb24261a-6334-4000-81ee-f99fb9df163c.jpg",
    "width": 1200,
    "height": 800,
    "outline": [
      [
        834.9,
        348.3
      ],
      [
        802.7,
        379.1
      ],
      [
        797,
        384.5
      ],
      [
        548.9,
        622.2
      ],
      [
        365.1,
        405.4
      ],
      [
        544.2,
        218
      ],
      [
        545.2,
        216.9
      ],
      [
        582.6,
        177.8
      ],
      [
        834.9,
        348.3
      ]
    ],
    "credit": "Aerial: USDA NAIP via USGS (public domain)"
  },
  {
    "propertyId": "9d1adcd4-e664-4d4b-aa2d-d8328072c61f",
    "src": "/aerials/9d1adcd4-e664-4d4b-aa2d-d8328072c61f.jpg",
    "width": 1200,
    "height": 800,
    "outline": [
      [
        832.1,
        330.3
      ],
      [
        509.5,
        577.8
      ],
      [
        486.2,
        595.7
      ],
      [
        451.6,
        622.2
      ],
      [
        431.4,
        576.1
      ],
      [
        383.4,
        466
      ],
      [
        367.9,
        430.6
      ],
      [
        398.9,
        407.8
      ],
      [
        711.2,
        177.8
      ],
      [
        832.1,
        330.3
      ]
    ],
    "credit": "Aerial: USDA NAIP via USGS (public domain)"
  },
  {
    "propertyId": "a5ddf92f-dcb2-4e8e-a48f-eeb1d04ce646",
    "src": "/aerials/a5ddf92f-dcb2-4e8e-a48f-eeb1d04ce646.jpg",
    "width": 1200,
    "height": 800,
    "outline": [
      [
        923.6,
        389.9
      ],
      [
        626.9,
        575.9
      ],
      [
        502.7,
        621.7
      ],
      [
        501.3,
        622.2
      ],
      [
        500.1,
        619.1
      ],
      [
        462.9,
        523.4
      ],
      [
        362.3,
        264.9
      ],
      [
        346.8,
        247
      ],
      [
        278.1,
        179.5
      ],
      [
        276.4,
        177.8
      ],
      [
        342.4,
        195.5
      ],
      [
        460.2,
        224.8
      ],
      [
        631.6,
        259.5
      ],
      [
        923.6,
        389.9
      ]
    ],
    "credit": "Aerial: USDA NAIP via USGS (public domain)"
  },
  {
    "propertyId": "3b12d583-4e71-4864-b949-fd384cd9897b",
    "src": "/aerials/3b12d583-4e71-4864-b949-fd384cd9897b.jpg",
    "width": 1200,
    "height": 800,
    "outline": [
      [
        731.6,
        218.5
      ],
      [
        633.3,
        622.2
      ],
      [
        502.7,
        590.6
      ],
      [
        468.4,
        582.3
      ],
      [
        566.3,
        177.8
      ],
      [
        602.4,
        186.7
      ],
      [
        731.6,
        218.5
      ]
    ],
    "credit": "Aerial: USDA NAIP via USGS (public domain)"
  },
  {
    "propertyId": "5955e813-1918-401e-867e-4d46c8ad5e61",
    "src": null,
    "width": 1200,
    "height": 800,
    "outline": null,
    "credit": "Aerial: USDA NAIP via USGS (public domain)"
  },
  {
    "propertyId": "ffe90278-3d7d-4306-a261-274165e3faf3",
    "src": null,
    "width": 1200,
    "height": 800,
    "outline": null,
    "credit": "Aerial: USDA NAIP via USGS (public domain)"
  }
];

export const HERO_AERIAL: HeroAerial = {
  "src": "/aerials/hero.jpg",
  "width": 2400,
  "height": 1350,
  "credit": "Aerial: USDA NAIP via USGS (public domain)"
};

const BY_ID: ReadonlyMap<string, LotAerial> = new Map(LOT_AERIALS.map((a) => [a.propertyId, a]));

export function aerialFor(propertyId: string): LotAerial | undefined {
  return BY_ID.get(propertyId);
}
