// Generated by tools/parcel-map/build.mjs. Do not edit by hand.
// Parcel outlines in feet, north up, centred on each parcel. Source: Sonoma County CDR_Parcels
// (planning purposes only, not parcel-specific decisions). A null outline = parcel not resolved.

export interface ParcelShape {
  readonly propertyId: string;
  readonly label: string;
  readonly apn: string | null;
  readonly acres: number | null;
  /** [x, y] in feet, y grows southward (screen orientation). Null when the parcel is unresolved. */
  readonly outline: readonly (readonly [number, number])[] | null;
}

export const PARCEL_SHAPES: readonly ParcelShape[] = [
  {
    "propertyId": "cb24261a-6334-4000-81ee-f99fb9df163c",
    "label": "35411 Fly Cloud Rd",
    "apn": "155-260-015",
    "acres": 0.50999999,
    "outline": [
      [
        113.2,
        -24.8
      ],
      [
        97.7,
        -10
      ],
      [
        95,
        -7.4
      ],
      [
        -24.7,
        106.4
      ],
      [
        -113.2,
        2.6
      ],
      [
        -26.9,
        -87.1
      ],
      [
        -26.4,
        -87.6
      ],
      [
        -8.4,
        -106.4
      ],
      [
        113.2,
        -24.8
      ]
    ]
  },
  {
    "propertyId": "9d1adcd4-e664-4d4b-aa2d-d8328072c61f",
    "label": "35604 Timber Ridge Rd",
    "apn": "155-260-003",
    "acres": 0.44999999,
    "outline": [
      [
        111.2,
        -33.1
      ],
      [
        -43.4,
        84.6
      ],
      [
        -54.5,
        93.1
      ],
      [
        -71.1,
        105.7
      ],
      [
        -80.8,
        83.8
      ],
      [
        -103.8,
        31.4
      ],
      [
        -111.2,
        14.6
      ],
      [
        -96.3,
        3.7
      ],
      [
        53.3,
        -105.7
      ],
      [
        111.2,
        -33.1
      ]
    ]
  },
  {
    "propertyId": "a5ddf92f-dcb2-4e8e-a48f-eeb1d04ce646",
    "label": "35995 Highway 1",
    "apn": "122-190-031",
    "acres": 2.23000002,
    "outline": [
      [
        280.2,
        -8.7
      ],
      [
        23.3,
        151.2
      ],
      [
        -84.3,
        190.6
      ],
      [
        -85.4,
        191.1
      ],
      [
        -86.5,
        188.4
      ],
      [
        -118.8,
        106.1
      ],
      [
        -205.9,
        -116.2
      ],
      [
        -219.2,
        -131.6
      ],
      [
        -278.7,
        -189.6
      ],
      [
        -280.2,
        -191.1
      ],
      [
        -223,
        -175.8
      ],
      [
        -121.1,
        -150.6
      ],
      [
        27.3,
        -120.8
      ],
      [
        280.2,
        -8.7
      ]
    ]
  },
  {
    "propertyId": "3b12d583-4e71-4864-b949-fd384cd9897b",
    "label": "39463 Leeward Rd",
    "apn": "156-270-012",
    "acres": 0.38999999,
    "outline": [
      [
        64.2,
        -87.9
      ],
      [
        16.3,
        107.6
      ],
      [
        -47.4,
        92.3
      ],
      [
        -64.2,
        88.3
      ],
      [
        -16.4,
        -107.6
      ],
      [
        1.2,
        -103.3
      ],
      [
        64.2,
        -87.9
      ]
    ]
  },
  {
    "propertyId": "5955e813-1918-401e-867e-4d46c8ad5e61",
    "label": "74 Burl Tree",
    "apn": null,
    "acres": null,
    "outline": null
  },
  {
    "propertyId": "ffe90278-3d7d-4306-a261-274165e3faf3",
    "label": "38065 Foothill Close",
    "apn": null,
    "acres": null,
    "outline": null
  }
];
